### ISSUE TITLE
Upgrade required version of  lazychaser/laravel-nestedset to v6 to fix error occurring with laravel >= 8.43

### ISSUE THREAD

**Issue by andrecolza** [rinvex/laravel-categories#102]
In Laravel 8.43 a new method is introduced in Illuminate\Database\Eloquent\Relations\Relation class.

    /**
     * Get the query builder that will contain the relationship constraints.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    protected function getRelationQuery()
    {
        return $this->query;
    }

This method conflicts with Kalnoy\Nestedset\BaseRelation class

    /**
     * @param EloquentBuilder $query
     * @param EloquentBuilder $parent
     * @param array $columns
     * @return mixed
     */
    public function getRelationQuery(
        EloquentBuilder $query, EloquentBuilder $parent,
        $columns = [ '*' ]
    ) {
        return $this->getRelationExistenceQuery($query, $parent, $columns);
    }

Since the method getRelationQuery() was never used inside package lazychaser/laravel-nestedset, the mantainer released a new version (v6.0) removing this method.

Please update your composer.json requiring v6 instead of v5 of package lazychaser/laravel-nestedset.

Thanks,
Andrea

**Comment by micross** [comment]
same issue

**Comment by pictus** [comment]
Having the same issue on Laravel 8.50.0, removed reinstalled `rinvex/laravel-categories`. Fresh installed again, but the issue is still the same 
```
Kalnoy\Nestedset\BaseRelation::getRelationQuery(Illuminate\Database\Eloquent\Builder $query, Illuminate\Database\Eloquent\Builder $parent, $columns = Array) should be compatible with Illuminate\Database\Eloquent\Relations\Relation::getRelationQuery()
```

**Comment by steven-fox** [comment]
I hate to say it, but you probably want to fork this repo for your projects and update it accordingly. The maintainer of this package has a track record of being pretty unresponsive.

You could also create your own, internal, version of this package from scratch to ditch several sub-dependencies if you don't actually need them (like `rinvex/laravel-support` after a few adjustments to the code in this package). This was the path we eventually took. Smooth sailing since.

**Comment by Omranic** [comment]
Thank you @andrecolza @micross @pictus for your patience, this is now fixed in latest release v5.0.6 please check and let me know if you've any other issues 🙂 

@steven-fox I hear you, and I appreciate raising your concerns. I understand how frustrating it could be if you're blocked by one of the dependencies used in your project for whatever reason, but I'm happy you got to remove the dependency by forking this open-source package. Anyway I hope it's useful to you, and please keep providing feedback that may help providing better support for everyone 👍

**Comment by steven-fox** [comment]
@Omranic No worries! We all appreciate you producing this package and making it available to the open source realm, so I apologize if my earlier message came off rudely. That wasn't my intention. I just wanted to let the other folks know that if they need an immediate solution for a production app, they'd likely need to fork this repo and handle it themselves.

Anyway, thanks for following up. Hope you have a great day!

**Comment by pictus** [comment]
@Omranic Ok, you updated to a newer version, but you also updated sluggable to version 3.0.x, which requires PHP8. Not all of us have PHP8.0 in production, is there a way, you can downgrade to 2.x?

**Comment by Omranic** [comment]
@pictus if you need the new fixes, but with the old composer dependencies support (old PHP version too), you'll need to fork this package then, and change `composer.json` to your needs.

Currently we're supporting latest PHP/Laravel/Composer Dependencies releases only. In many cases you'll find a tag that you can lock your dependencies to, for example you can still use this package and lock it to this revision: 526cb6696d7f5502acaacfced92c10c330de340d
