### ISSUE TITLE
Error on using normal create method with no slug

### ISSUE THREAD

**Issue by NassarX** [rinvex/laravel-categories#3]
Hi @Omranic 

Trying to create new category using normal eloquent `Category::create` method every time it redirect back to create page and no categories created .

The problem was that I don't send **slug** attribute with other category data and found that you made it as a **required**
 `        $this->setRules([
            'slug' => 'required|alpha_dash|unique:'.config('rinvex.categorizable.tables.categories').',slug',
        ]);
`

So wonder why **required** although make use of [spatie/laravel-sluggable](https://github.com/spatie/laravel-sluggable) to handle  create slug from category name.

**Comment by Omranic** [comment]
It should be auto created if not supplied, let me check this & get back to you 👍

**Comment by pilishen** [comment]
got the same problem

**Comment by Yario** [comment]
Is there way to disable translation totally? It's unnecessary for my purpose and just make a mess

**Comment by Omranic** [comment]
@NassarX The **slug** issue should be fixed in latest releases of this package. Please feel free to reopen this issue or a new one if you need further assistance 🙂 

@Yario You can ignore translations and use the package like normal, translations are handled gracefully, automagically behind scenes. And if you still need to remove it totally, then you can override the model & modify the migrations, or even fork the whole package if required 🙌
