### ISSUE TITLE
Laravel 5.8 Support

### ISSUE THREAD

**Issue by fernas** [rinvex/laravel-categories#45]
It seems that this package is not compatible with Laravel 5.8:

`Conclusion: don't install laravel/framework v5.8.2`

**Comment by Omranic** [comment]
Will add support to Laravel 5.8 within the next 48 hrs ;)

**Comment by JoshuaBedford** [comment]
This has not been fixed (not for me anyway).

I am on Laravel 5.8.4 and run `composer require rinvex/laravel-categories`. It fails because "rinvex/laravel-categories v1.0.0 requires illuminate/support ~5.7.0" or "rinvex/laravel-categories v1.0.1 requires illuminate/support ~5.7.0".

I looked at your composer.json, and it seems to specify illuminate/support 5.8. Perhaps Laravel 5.8 support hasn't been released yet?

Edit: I found [release 2.0 here](https://github.com/rinvex/laravel-categories/releases/tag/v2.0.0). Not sure why it doesn't pull that in?

**Comment by drbyte** [comment]
@JoshuaBedford What's in your `composer.json`? (particularly for this rinvex package, but posting the entire thing might be helpful for troubleshooting)

**Comment by drbyte** [comment]
@JoshuaBedford What's in your `composer.json`? (particularly for this rinvex package, but posting the entire thing might be helpful for troubleshooting)

**Comment by JoshuaBedford** [comment]
> @JoshuaBedford What's in your `composer.json`? (particularly for this rinvex package, but posting the entire thing might be helpful for troubleshooting)

When I specified `"rinvex/laravel-categories": "^2.0"` in my composer.json it began working, but when I ran `composer require rinvex/laravel-categories` it attempted to grab the version 1.*

I think the issue might have been in my composer.json, my "require" had `"php": "^7.1.3"` which thoroughly confused the package (I upgraded to Laravel 5.8 and forgot to change that, I presume). The composer.json below worked.

I apologize if this was my fault and a false alarm! 

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^7.2",
        "alaouy/youtube": "^2.2",
        "fideloper/proxy": "^4.0",
        "joshuabedford/laravel-word-filter": "^1.0",
        "laravel/cashier": "^9.1",
        "laravel/framework": "5.8.*",
        "laravel/passport": "^7.2",
        "laravel/tinker": "^1.0",
        "mpociot/laravel-apidoc-generator": "^3.4",
        "sammyk/laravel-facebook-sdk": "^3.5",
        "spatie/laravel-permission": "^2.33",
        "rinvex/laravel-categories": "^2.0"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": ["database/seeds", "database/factories"]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": ["@php artisan key:generate --ansi"]
    }
}
```

**Comment by drbyte** [comment]
@JoshuaBedford thanks for clarifying.

Yes, composer combinations can sometimes give unexpected results. Most of the time composer is correct. In some rare occasions it can be helpful to manually delete the `/vendor` folder so that it rebuilds its complete dependency map irrespective of what had been installed already.
But, as you've done, reviewing all the dependencies, is the first and best fix.
Cheers

**Comment by JoshuaBedford** [comment]
@drbyte thanks for the quick response and patient explanation!
