### ISSUE TITLE
Add migrations to the common flow

### ISSUE THREAD

**Issue by giovannipds** [rinvex/laravel-categories#57]
Hi there!
First of all, congrats to the package!

There's something that bites me. Why `php artisan rinvex:migrate:categories` isn't on common flow of the other `php artisan migrate` actions?

I mean, when I'm running `php artisan migrate:fresh`, for example, I have to run categories migrations separately.

That's probably because laravel categories migrations are wrapped by `rinvex` and `laravel-categories` directories - which, is **good for organization**, I like it, but, **if it won't work with the other artisan migrate actions**, I'd prefer to dis-consider it!

Any thoughts about it? Should we unwrap it from the directories or there's another way to solve this? Thanks in advance!

**Comment by Omranic** [comment]
Just publish the migrations, and everything will work as expected 🙂 
`php artisan rinvex:publish:categories --resource=migrations`

**Comment by giovannipds** [comment]
I don't know if you're getting what I meant.

I did what you said but when running `php artisan migrate` or `php artisan migrate:fresh` later by another dev or environment, rinvex categories is not included 'cause they're wrapped on dir `rinvex/laravel-categories`.

It should publish without the dirs (like other packages do). Or am I missing something?

**Comment by Omranic** [comment]
Hello @giovannipds 
In fact, we had what you suggested in a previous release, but because of other use cases (check conversations here #16 & #27 and others) we changed that behaviour. But after a while I believe both ways have there pros and cons, that's why we're reverting back the old behavior of auto-registering migrations, but with extra feature of being able to optionally disable that feature using config option.

**Comment by giovannipds** [comment]
@Omranic very nice to hear that! Thank you.
